# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_url = "/home/msnd/virtualbox.box"
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.define "sclamS" do |server|
    server.vm.hostname = "sclamS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |v|
      v.name = "sclamS"
      v.memory = 3072
    end
    server.vm.provision "shell", privileged: false, path: "./scripts/start.sh"
  end
end 
