# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_url = "/home/msnd/stuff/virtualbox7.box"

  config.vm.define "sclamS" do |server|
    server.vm.hostname = "sclamS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |v|
      v.name = "sclamS"
      v.memory = 512
      v.cpus = 1
    end
    server.vm.provision :shell, inline: <<-SHELL
      #echo "[SCRIPT] Copy ssh key"
      #cat /tmp/id_rsa.pub >> ~/.ssh/authorized_keys
      echo "[SCRIPT] Install k3s"
      curl -sfL https://get.k3s.io/ | sh -s - --write-kubeconfig-mode 644
      echo "[SCRIPT] Copy token"
      echo $(sudo cat /var/lib/rancher/k3s/server/node-token) > /vagrant/.token
      echo "[SCRIPT] Waiting"
      kubectl wait --for=condition=Ready node/sclams
    SHELL
    server.trigger.after :up do |trigger|
      trigger.run = {inline: "vagrant scp sclamS:/vagrant/.token ."}
    end
  end

  config.vm.define "sclamSW" do |worker|
    worker.vm.hostname = "slcamSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |v|
      v.name = "sclamSW"
      v.memory = 512
      v.cpus = 1
    end
    worker.vm.provision "file", source: ".token", destination: "/vagrant/.token"
    worker.vm.provision :shell, inline: <<-SHELL
      echo "[SCRIPT] Add master to /etc/hosts"
      echo "192.168.56.110 sclamS" >> /etc/hosts
      echo "[SCRIPT] Install k3s"
      curl -sfL https://get.k3s.io | K3S_URL=https://sclamS:6443 K3S_TOKEN=$(cat /vagrant/.token) sh -
    SHELL
    worker.trigger.after :up do |trigger|
      trigger.run = {inline: "rm .token"}
    end
  end
end
